baseURL = "https://blog.envyt.me"
languageCode = "en-us"
title = "Me, against my thoughts"
theme = "PaperMod"

[markup.goldmark.renderer]
  unsafe = true

[params]
  defaultTheme = "light"
  mainSections = ["posts"]
  
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 20
